In [45]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [46]:
import os
import pandas as pd 
from prospectdataset import process_pcp_data

# Individual processing

## Processing multi_ptm dataset

In [47]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/multi_ptm",
    file_name="multi_ptm_processed.parquet"
)

Starting data processing...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_acetylated_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_citrullination_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_imp_pSTY_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_monomethyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_OGalNAc_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_OGlcNAc_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_pS_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_pT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_pyroGlu_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_pY_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_mod_ubi_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm/TUM_nterm_ac_meta_data.parquet...
Processed batch of 42 files.
Processed 12 files from /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/multi_ptm.
No TMT data detected for processing.
Filtering rows based on andromeda_score >= 70...
Filtering DataFrame to keep columns: ['modified_sequence', 'precursor_charge', 'precursor_intensity', 'raw_file', 'scan_number', 'package']...
Dropping rows with NaN values in precursor_intensity...
Filtering DataFrame for desired charge states...
Aggregating DataFrame by 'modified_sequence'...
Removing rare sequences with lengths less than 100 occurrences...
Removed 386 of 212565 sequences.
Selecting the most abundant charge by max intensity...
Generating charge state labels...
Computing intensity distributions...
Saving DataFrame as Parquet file at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/multi_ptm/multi_ptm_processed.parquet...
File saved successfully at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/multi_ptm/multi_ptm_processed.parquet
________________________________________________________________________________
Data processing completed.
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 212179 entries, 0 to 212564
Data columns (total 7 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   modified_sequence           212179 non-null  object
 1   raw_file                    212179 non-null  object
 2   scan_number                 212179 non-null  object
 3   package                     212179 non-null  object
 4   most_abundant_charge_state  212179 non-null  object
 5   observed_charge_states      212179 non-null  object
 6   charge_state_dist           212179 non-null  object
dtypes: object(7)
memory usage: 21.0+ MB
None

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAAAAAAAAR[UNIMOD:34],[02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2x...,"[8031, 8032, 8033, 8065, 8066, 8067, 8096, 809...",[TUM_mod_monomethyl],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
1,AAAAAAAAAVS[UNIMOD:21]R,[02747a_GD6-TUM_mod_pS_42_01_01-2xIT_2xHCD-1h-...,"[12002, 12003, 12004, 12005, 12038, 12039, 120...",[TUM_mod_pS],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
2,AAAAAAAAVPSAGPAGPAPT[UNIMOD:21]SAAGR,[02588a_BD6-TUM_mod_pT_42_01_01-2xIT_2xHCD-1h-R1],"[22779, 22780, 22804]",[TUM_mod_pT],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
3,AAAAAAALQAK,"[02468b_BD1-TUM_mod_ubi_37_01_01-DDA-1h-R1, 02...","[16343, 16345, 16527, 16534, 16545, 16555, 167...",[TUM_mod_ubi],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
4,AAAAAAALQAKSDEK,[02195a_GD7-TUM_mod_acetylated_43_01_01-DDA-1h...,"[13272, 13458]",[TUM_mod_acetylated],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...
212560,[UNIMOD:1]YWSNQITRRLGER,"[03512a_BC4-TUM_nterm_ac_4_01_01-3xHCD-1h-R1, ...","[36412, 44973, 46494, 46574, 46584, 47120, 47255]",[TUM_nterm_ac],"[0, 0, 1, 0, 0, 0]","[0, 1, 1, 0, 0, 0]","[0.0, 0.12101622731541073, 0.8789837726845893,..."
212561,[UNIMOD:1]YYGDDPR[UNIMOD:7]VHR,[02207a_BD1-TUM_mod_citrullination_s_1_01_01-D...,"[22037, 22038]",[TUM_mod_citrullination],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
212562,[UNIMOD:1]YYGGGSEGGR[UNIMOD:7]APK,[02207a_GA8-TUM_mod_citrullination_l_8_01_01-2...,"[23455, 23456, 23458, 23500, 23501, 23502, 235...",[TUM_mod_citrullination],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
212563,[UNIMOD:1]YYKEIEDR[UNIMOD:7]QK,[02207a_BA3-TUM_mod_citrullination_l_3_01_01-D...,"[24710, 24711, 28604, 28605, 28786, 30710, 307...",[TUM_mod_citrullination],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
212564,[UNIMOD:1]YYVTIIDAPGHR[UNIMOD:7]DFIK,[02207a_GB1-TUM_mod_citrullination_l_13_01_01-...,"[50161, 50213, 50214, 50247, 50248]",[TUM_mod_citrullination],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

## Processing propect dataset

In [48]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/prospect",
    file_name="prospect_processed.parquet",
    process_test_ptm_only=False
)

Starting data processing...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/Thermo_SRM_Pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_aspn_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_first_pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_HLA2_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_HLA_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_isoform_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_lysn_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_missing_first_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_proteo_TMT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_second_addon_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_second_pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect/TUM_third_pool_meta_data.parquet...
Processed batch of 42 files.
Processed 12 files from /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/prospect.
No TMT data detected for processing.
Filtering rows based on andromeda_score >= 70...
Filtering DataFrame to keep columns: ['modified_sequence', 'precursor_charge', 'precursor_intensity', 'raw_file', 'scan_number', 'package']...
Dropping rows with NaN values in precursor_intensity...
Filtering DataFrame for desired charge states...
Aggregating DataFrame by 'modified_sequence'...
Removing rare sequences with lengths less than 100 occurrences...
Removed 706 of 758526 sequences.
Selecting the most abundant charge by max intensity...
Generating charge state labels...
Computing intensity distributions...
Saving DataFrame as Parquet file at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/prospect/prospect_processed.parquet...
File saved successfully at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/prospect/prospect_processed.parquet
________________________________________________________________________________
Data processing completed.
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 757820 entries, 0 to 758525
Data columns (total 7 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   modified_sequence           757820 non-null  object
 1   raw_file                    757820 non-null  object
 2   scan_number                 757820 non-null  object
 3   package                     757820 non-null  object
 4   most_abundant_charge_state  757820 non-null  object
 5   observed_charge_states      757820 non-null  object
 6   charge_state_dist           757820 non-null  object
dtypes: object(7)
memory usage: 62.4+ MB
None

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAAAAAAAAAAAAAAGLGLGP,[03035a_GH4-TUM_HLA2_88_01_01-2xIT_2xHCD-1h-R1...,"[48048, 48049, 48050, 48057, 48073, 48074, 480...",[TUM_HLA2],"[0, 1, 0, 0, 0, 0]","[1, 1, 1, 0, 0, 0]","[0.0014942136737631886, 0.977159622342211, 0.0..."
1,AAAAAAAAAAAAAAAASAGGK,[01974c_BA2-TUM_missing_first_9_01_01-2xIT_2xH...,"[30370, 30371, 30372, 30373, 30411, 30412, 304...",[TUM_missing_first],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
2,AAAAAAAAAAAAAAAGAGAGAK,[01709a_GG2-TUM_first_pool_113_01_01-2xIT_2xHC...,"[27942, 27943, 27944, 27945]",[TUM_first_pool],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
3,AAAAAAAAAAAAAAASGFAYPGTSER,[01709a_GD3-TUM_first_pool_118_01_01-2xIT_2xHC...,"[35970, 35971, 35972, 36087, 36088, 36089, 361...",[TUM_first_pool],"[0, 1, 0, 0, 0, 0]","[0, 1, 1, 0, 0, 0]","[0.0, 0.9879325512697509, 0.012067448730249095..."
4,AAAAAAAAAAAAAAG,[03035a_GD2-TUM_HLA2_38_01_01-2xIT_2xHCD-1h-R1...,"[27502, 27503, 27504, 27533, 27534, 27535, 275...",[TUM_HLA2],"[1, 0, 0, 0, 0, 0]","[1, 0, 0, 0, 0, 0]","[1.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...
758521,YYYVGFAYL,"[02445d_BE9-TUM_HLA_57_01_01-2xIT_2xHCD-1h-R4,...","[58551, 58570, 58607, 58702, 76387, 76388, 764...",[TUM_HLA],"[1, 0, 0, 0, 0, 0]","[1, 1, 0, 0, 0, 0]","[0.9838318904718528, 0.01616810952814731, 0.0,..."
758522,YYYVPADFVEYEK,[01640c_BG8-Thermo_SRM_Pool_63_01_01-2xIT_2xHC...,"[36471, 36472, 36473, 36514, 36515, 36516, 365...",[Thermo_SRM_Pool],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
758523,YYYVQNVYTPVDEHVYPDHR,[01709a_GB2-TUM_first_pool_108_01_01-2xIT_2xHC...,"[24609, 24610, 26812, 26813, 26814, 26815, 290...",[TUM_first_pool],"[0, 0, 0, 1, 0, 0]","[0, 0, 1, 1, 0, 0]","[0.0, 0.0, 0.7274547182194011, 0.2725452817805..."
758524,YYYWVINPADSSGITPK,[02080d_GA2-TUM_isoform_98_01_01-2xIT_2xHCD-1h...,"[44420, 44421, 44445, 44446, 44963, 45403, 454...",[TUM_isoform],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
758525,YYYYIREA,"[02445a_BH6-TUM_HLA_90_01_01-DDA-1h-R1, 02445d...","[28302, 28303, 28304, 28340, 28341, 28342, 283...",[TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

In [14]:
df = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/prospect", engine="pyarrow")

In [15]:
df["charge_state_dist"].iloc[0]

array([0.00149421, 0.97715962, 0.02134616, 0.        , 0.        ,
       0.        ])

## Process tmt dataset

In [49]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt",
    file_name="tmt_processed.parquet",
    process_test_ptm_only=False
)

Starting data processing...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_Thermo_SRM_Pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_aspn_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_first_pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_HLA_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_isoform_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_lysn_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_missing_first_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_proteo_TMT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_second_addon_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_second_pool_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt/TMT_TUM_third_pool_meta_data.parquet...
Processed batch of 42 files.
Processed 11 files from /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt.
Processing TMT data to remove sequences without UNIMOD:737 annotations...
Removed 3937456 sequences without UNIMOD:737 annotations from TMT data.
Filtering rows based on andromeda_score >= 70...
Filtering DataFrame to keep columns: ['modified_sequence', 'precursor_charge', 'precursor_intensity', 'raw_file', 'scan_number', 'package']...
Dropping rows with NaN values in precursor_intensity...
Filtering DataFrame for desired charge states...
Aggregating DataFrame by 'modified_sequence'...
Removing rare sequences with lengths less than 100 occurrences...
Removed 643 of 589622 sequences.
Selecting the most abundant charge by max intensity...
Generating charge state labels...
Computing intensity distributions...
Saving DataFrame as Parquet file at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt/tmt_processed.parquet...
File saved successfully at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt/tmt_processed.parquet
________________________________________________________________________________
Data processing completed.
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 588979 entries, 0 to 589621
Data columns (total 7 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   modified_sequence           588979 non-null  object
 1   raw_file                    588979 non-null  object
 2   scan_number                 588979 non-null  object
 3   package                     588979 non-null  object
 4   most_abundant_charge_state  588979 non-null  object
 5   observed_charge_states      588979 non-null  object
 6   charge_state_dist           588979 non-null  object
dtypes: object(7)
memory usage: 52.1+ MB
None

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAAAAAGAGAGAK[UNIMOD:737],[03925_BE2-TMT_TUM_HLA2_146_01_01-TMT2-1h-R1],[10182],[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
1,AAAAAAGSGPK[UNIMOD:737]D,"[03924_GE10-TMT_TUM_HLA2_58_01_01-TMT1-1h-R1, ...","[8135, 8151, 8192, 8240, 8823, 9097, 9155, 9287]",[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
2,AAAAAGSGPK[UNIMOD:737]D,[03924_GE10-TMT_TUM_HLA2_58_01_01-TMT1-1h-R1],[8665],[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
3,AAAERPGEAAVASSPSK[UNIMOD:737],[03925_BE2-TMT_TUM_HLA2_146_01_01-TMT1-1h-R1],[12401],[TMT_TUM_HLA],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
4,AAAFAGIK[UNIMOD:737]PFLALYM[UNIMOD:35],[03925_BE11-TMT_TUM_HLA2_155_01_01-TMT1-1h-R1],[68338],[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...
589617,[UNIMOD:737]-YYYVGFAYL,"[02527_BE9-TMT_TUM_HLA_57_01_01-TMT1-1h-R1, 02...","[66780, 66791, 66795, 66799, 66811, 66845, 668...",[TMT_TUM_HLA],"[1, 0, 0, 0, 0, 0]","[1, 1, 0, 0, 0, 0]","[0.6899395463844208, 0.3100604536155793, 0.0, ..."
589618,[UNIMOD:737]-YYYVPADFVEYEK[UNIMOD:737],[02244b_GG8-TMT_Thermo_SRM_Pool_63_01_01-TMT1-...,"[47519, 51909, 51952, 52011, 52056, 52078]",[TMT_Thermo_SRM_Pool],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
589619,[UNIMOD:737]-YYYVRDVPYDVLAS,[03925_BA5-TMT_TUM_HLA2_101_01_01-TMT1-1h-R1],"[45908, 45922]",[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
589620,[UNIMOD:737]-YYYWVINPADSSGITPK[UNIMOD:737],[02246_BA2-TMT_TUM_isoform_98_01_01-TMT1-1h-R1...,"[46053, 46057, 46081, 46093, 46159, 46222, 56367]",[TMT_TUM_isoform],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
589621,[UNIMOD:737]-YYYYIREA,"[02527_BH6-TMT_TUM_HLA_90_01_01-TMT1-1h-R1, 02...","[38566, 38567, 38618, 38619, 42785, 42823, 428...",[TMT_TUM_HLA],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

## Process tmt_ptm dataset

In [50]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt_ptm",
    file_name="tmt_ptm_processed.parquet",
)

Starting data processing...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_acetylated_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_imp_pSTY_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_monomethyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_pS_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_pT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm/TMT_TUM_mod_pY_meta_data.parquet...
Processed batch of 42 files.
Processed 6 files from /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/tmt_ptm.
No TMT data detected for processing.
Filtering rows based on andromeda_score >= 70...
Filtering DataFrame to keep columns: ['modified_sequence', 'precursor_charge', 'precursor_intensity', 'raw_file', 'scan_number', 'package']...
Dropping rows with NaN values in precursor_intensity...
Filtering DataFrame for desired charge states...
Aggregating DataFrame by 'modified_sequence'...
Removing rare sequences with lengths less than 100 occurrences...
Removed 946 of 74165 sequences.
Selecting the most abundant charge by max intensity...
Generating charge state labels...
Computing intensity distributions...
Saving DataFrame as Parquet file at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt_ptm/tmt_ptm_processed.parquet...
File saved successfully at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/tmt_ptm/tmt_ptm_processed.parquet
________________________________________________________________________________
Data processing completed.
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 73219 entries, 0 to 74164
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   modified_sequence           73219 non-null  object
 1   raw_file                    73219 non-null  object
 2   scan_number                 73219 non-null  object
 3   package                     73219 non-null  object
 4   most_abundant_charge_state  73219 non-null  object
 5   observed_charge_states      73219 non-null  object
 6   charge_state_dist           73219 non-null  object
dtypes: object(7)
memory usage: 6.5+ MB
None

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAAAGGK[UNIMOD:737]K[UNIMOD:1]R,[03920_GA12-TMT_TUM_mod_acetylated_12_01_01-TM...,[8368],[TMT_TUM_mod_acetylated],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
1,AAAGY[UNIMOD:21]YPR,"[02523_BA7-TMT_TUM_mod_pY_7_01_01-TMT1-1h-R1, ...","[12674, 12676]",[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
2,AAAHHYGAQC[UNIMOD:4]DK[UNIMOD:1]PNK,[03920_GC6-TMT_TUM_mod_acetylated_30_01_01-TMT...,[2473],[TMT_TUM_mod_acetylated],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
3,AAAKK[UNIMOD:1]M[UNIMOD:35]EEVEAR,[03920_GB8-TMT_TUM_mod_acetylated_20_01_01-TMT...,[3436],[TMT_TUM_mod_acetylated],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
4,AAAK[UNIMOD:1]K[UNIMOD:1]M[UNIMOD:35]EEVEAR,[03920_GB8-TMT_TUM_mod_acetylated_20_01_01-TMT...,[9222],[TMT_TUM_mod_acetylated],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...
74160,[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]SYLM[UNIMO...,[02523_BA4-TMT_TUM_mod_pY_4_01_01-TMT1-1h-R1],"[29509, 29578, 29595, 29648, 29662, 29714, 297...",[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
74161,[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]TPTISR,"[02523_BA5-TMT_TUM_mod_pY_5_01_01-TMT1-1h-R1, ...","[21382, 21383, 21384, 21385, 21429, 21430, 214...",[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
74162,[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]TPVLAK[UNI...,"[02523_BA3-TMT_TUM_mod_pY_3_01_01-TMT1-1h-R1, ...","[37858, 37859, 37860, 37915, 37916, 37917, 379...",[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
74163,[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]VTIIDAPGHR,"[02523_BB5-TMT_TUM_mod_pY_17_01_01-TMT1-1h-R1,...","[33659, 33926, 33998, 34046]",[TMT_TUM_mod_pY],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
74164,[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]YQLNSK[UNI...,"[02523_BA7-TMT_TUM_mod_pY_7_01_01-TMT1-1h-R1, ...","[29862, 29863, 29911, 33108, 33180, 33248, 333...",[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

## Process test_ptm dataset

In [51]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/test_ptm",
    file_name="test_ptm_processed.parquet",
    process_test_ptm_only=True
)

Starting data processing...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Acetyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Biotin_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Butyryl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Crotonyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Dimethyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Formyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Glutaryl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_GlyGly_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Hydroxyisobut_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Malonyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Methyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Propion_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Succinyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Trimethyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Kmod_Unmod_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Pmod_Hydroxypro_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Rmod_Citrullin_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Rmod_Dimethyl-as_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Rmod_Dimethyl-sym_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Rmod_Methyl_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Rmod_Unmod_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TMT_TUM_mod_ubi_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TMT_TUM_perm_pS_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TMT_TUM_perm_pT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TMT_TUM_perm_pY_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TUM_combPTM_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TUM_perm_pS_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TUM_perm_pT_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/TUM_perm_pY_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Ymod_Nitrotyr_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Ymod_Phospho_meta_data.parquet...
Reading /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm/Ymod_Unmod_meta_data.parquet...
Processed batch of 42 files.
Processed 32 files from /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data/test_ptm.
No TMT data detected for processing.
Filtering rows based on andromeda_score >= 70...
Filtering DataFrame to keep columns: ['modified_sequence', 'precursor_charge', 'precursor_intensity', 'raw_file', 'scan_number', 'package']...
Dropping rows with NaN values in precursor_intensity...
Filtering DataFrame for desired charge states...
Aggregating DataFrame by 'modified_sequence'...
Removing rare sequences with lengths less than 100 occurrences...
Removed 1117 of 43145 sequences.
Selecting the most abundant charge by max intensity...
Generating charge state labels...
Computing intensity distributions...
Saving DataFrame as Parquet file at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/test_ptm/test_ptm_processed.parquet...
File saved successfully at /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/test_ptm/test_ptm_processed.parquet
________________________________________________________________________________
Data processing completed.
________________________________________________________________________________
<class 'pandas.core.frame.DataFrame'>
Index: 42028 entries, 0 to 43144
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   modified_sequence           42028 non-null  object
 1   raw_file                    42028 non-null  object
 2   scan_number                 42028 non-null  object
 3   package                     42028 non-null  object
 4   most_abundant_charge_state  42028 non-null  object
 5   observed_charge_states      42028 non-null  object
 6   charge_state_dist           42028 non-null  object
dtypes: object(7)
memory usage: 3.6+ MB
None

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAGEDYK[UNIMOD:737],[02526_BC5-TMT_TUM_mod_ubi_29_01_01-TMT1-1h-R3],[7709],[TMT_TUM_mod_ubi],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
1,AAAM[UNIMOD:35]ANNLQK[UNIMOD:737][UNIMOD:121]G...,[02526_BE4-TMT_TUM_mod_ubi_52_01_01-TMT1-1h-R3],[4432],[TMT_TUM_mod_ubi],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
2,AAEEPSK[UNIMOD:737]VEEK[UNIMOD:737][UNIMOD:121...,[02526_BC3-TMT_TUM_mod_ubi_27_01_01-TMT1-1h-R3...,"[9915, 9980, 9983]",[TMT_TUM_mod_ubi],"[0, 0, 0, 1, 0, 0]","[0, 0, 0, 1, 0, 0]","[0.0, 0.0, 0.0, 1.0, 0.0, 0.0]"
3,AAEQYTPK[UNIMOD:737][UNIMOD:121]AK[UNIMOD:737],[02526_BA12-TMT_TUM_mod_ubi_12_01_01-TMT1-1h-R3],[15083],[TMT_TUM_mod_ubi],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
4,AAESETPGK[UNIMOD:737][UNIMOD:121]SPEK[UNIMOD:737],[02526_BC10-TMT_TUM_mod_ubi_34_01_01-TMT1-1h-R...,"[6172, 6314]",[TMT_TUM_mod_ubi],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
...,...,...,...,...,...,...,...
43140,[UNIMOD:737]Y[UNIMOD:21]YGIPYIETSAK[UNIMOD:737],[03686_GH11-TMT_TUM_perm_pY_3_01_01-TMT1-1h-R1...,"[44466, 44467, 44506, 44507, 44550, 44551, 446...",[TMT_TUM_perm_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
43141,[UNIMOD:737]Y[UNIMOD:21]YHLQIVTK[UNIMOD:737],"[03686_GH9-TMT_TUM_perm_pY_1_01_01-TMT1-1h-R1,...","[29458, 29459, 29527, 29528, 33838, 33839, 338...",[TMT_TUM_perm_pY],"[0, 0, 1, 0, 0, 0]","[0, 1, 1, 0, 0, 0]","[0.0, 0.20828412487457829, 0.7917158751254217,..."
43142,[UNIMOD:737]Y[UNIMOD:21]YSSPLLIHEQFGC[UNIMOD:4...,"[03686_GH9-TMT_TUM_perm_pY_1_01_01-TMT1-1h-R1,...","[44584, 44636, 45012, 45050, 45052, 45063, 450...",[TMT_TUM_perm_pY],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"
43143,[UNIMOD:737]Y[UNIMOD:21]YVDTGGVSR,[03686_GH11-TMT_TUM_perm_pY_3_01_01-TMT1-1h-R1...,"[20477, 20478, 20479, 20480, 20526, 20527, 205...",[TMT_TUM_perm_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
43144,[UNIMOD:737]Y[UNIMOD:21]YVTMTATK[UNIMOD:737],[03686_GH12-TMT_TUM_perm_pY_4_01_01-TMT1-1h-R1...,"[30173, 30174, 30175, 30185, 30186, 30187, 302...",[TMT_TUM_perm_pY],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"

# Combining individually processed files

In [55]:
def combine_parquet_files(directory_path="processed_data", exclude_dir="test_ptm", output_file="combined_data.parquet"):
    """
    Combines all Parquet files in subdirectories of the specified directory into one DataFrame,
    excluding files in the specified directory to exclude.

    Parameters:
    directory_path (str): Path to the main directory containing subdirectories with Parquet files.
    exclude_dir (str): Name of the subdirectory to exclude.
    output_file (str): Name of the output Parquet file to save the combined DataFrame.

    Returns:
    pd.DataFrame: The combined DataFrame.
    """
    all_files = []
    for root, dirs, files in os.walk(directory_path):
        for file in files:
            if file.endswith(".parquet") and exclude_dir not in root:
                all_files.append(os.path.join(root, file))

    combined_df = pd.DataFrame()
    combined_df = pd.concat([pd.read_parquet(file, engine="pyarrow") for file in all_files], ignore_index=True)
    # for file in all_files:
    #     try:
    #         df = pd.read_parquet(file, engine="pyarrow")
    #         combined_df = pd.concat([combined_df, df], ignore_index=True)
    #         print(f"Successfully read and combined: {file}")
    #     except Exception as e:
    #         print(f"Error reading {file}: {e}")

    # try:
    #     # Convert columns with mixed data types to string -- avoiding saving issues
    #     for col in combined_df.columns:
    #         if combined_df[col].dtype == 'object':
    #             combined_df[col] = combined_df[col].astype(str)
        
    output_path = os.path.join(directory_path, output_file)
    combined_df.to_parquet(output_path, engine="pyarrow", index=False)
    print(f"Combined data saved to: {output_path}")
    # except Exception as e:
    #     print(f"Error saving combined data: {e}")

    return combined_df

In [58]:
combined_df = combine_parquet_files(directory_path="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data", exclude_dir="test_ptm", output_file="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_processed.parquet")

Combined data saved to: /mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_processed.parquet

In [57]:
df = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_pyarrow.parquet", engine="pyarrow")

In [60]:
df_test = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/test_ptm/test_ptm_processed.parquet", engine="pyarrow")

In [61]:
len(df_test)

42028

In [40]:
combined_df.charge_state_dist.iloc[0]

array([0., 1., 0., 0., 0., 0.])

In [31]:
for c in combined_df.columns:
    if c == "modified_sequence": 
        continue
    combined_df[c] = combined_df[c].apply(list)

In [32]:
# combine one by one 
combined_df[["charge_state_dist", "modified_sequence", "package", "observed_charge_states", "scan_number", "most_abundant_charge_state", "raw_file"]].to_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow", index=False)

In [30]:
import numpy as np
combined_df.raw_file = combined_df.raw_file.apply(lambda x: np.unique(x))

In [20]:
combined_df.raw_file.apply(lambda x: type(x)).value_counts()

raw_file
<class 'list'>    1632197
Name: count, dtype: int64

In [33]:
temp = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow")

In [34]:
temp

,charge_state_dist,modified_sequence,package,observed_charge_states,scan_number,most_abundant_charge_state,raw_file
0,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",AAAAAAAAAAR[UNIMOD:34],[TUM_mod_monomethyl],"[0, 1, 0, 0, 0, 0]","[9033, 9078, 9119, 9164, 9121, 9120, 9034, 916...","[0, 1, 0, 0, 0, 0]",[02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2x...
1,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",AAAAAAAAAVS[UNIMOD:21]R,[TUM_mod_pS],"[0, 1, 0, 0, 0, 0]","[16293, 16304, 12004, 12005, 12003, 12002, 120...","[0, 1, 0, 0, 0, 0]",[02747a_GD6-TUM_mod_pS_42_01_01-2xIT_2xHCD-1h-...
2,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",AAAAAAAAVPSAGPAGPAPT[UNIMOD:21]SAAGR,[TUM_mod_pT],"[0, 1, 0, 0, 0, 0]","[22779, 22804, 22780]","[0, 1, 0, 0, 0, 0]",[02588a_BD6-TUM_mod_pT_42_01_01-2xIT_2xHCD-1h-R1]
3,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",AAAAAAALQAK,[TUM_mod_ubi],"[0, 1, 0, 0, 0, 0]","[16731, 16740, 16908, 16912, 16343, 16345, 165...","[0, 1, 0, 0, 0, 0]","[02468b_BD1-TUM_mod_ubi_37_01_01-DDA-1h-R1, 02..."
4,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]",AAAAAAALQAKSDEK,[TUM_mod_acetylated],"[0, 0, 1, 0, 0, 0]","[13272, 13458]","[0, 0, 1, 0, 0, 0]",[02195a_GD7-TUM_mod_acetylated_43_01_01-DDA-1h...
...,...,...,...,...,...,...,...
1632192,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]SYLM[UNIMO...,[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[29778, 29714, 29648, 29509, 29578, 29856, 298...","[0, 1, 0, 0, 0, 0]",[02523_BA4-TMT_TUM_mod_pY_4_01_01-TMT1-1h-R1]
1632193,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]TPTISR,[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[23304, 23244, 23310, 23390, 23389, 23155, 233...","[0, 1, 0, 0, 0, 0]","[02523_BA5-TMT_TUM_mod_pY_5_01_01-TMT1-1h-R1, ..."
1632194,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]TPVLAK[UNI...,[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[42785, 42557, 42701, 42494, 42712, 42624, 427...","[0, 1, 0, 0, 0, 0]","[02523_BA3-TMT_TUM_mod_pY_3_01_01-TMT1-1h-R1, ..."
1632195,"[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]",[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]VTIIDAPGHR,[TMT_TUM_mod_pY],"[0, 0, 1, 0, 0, 0]","[33998, 33926, 34046, 33659, 33998, 33926, 340...","[0, 0, 1, 0, 0, 0]","[02523_BB5-TMT_TUM_mod_pY_17_01_01-TMT1-1h-R1,..."
1632196,"[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]",[UNIMOD:737]Y[UNIMOD:21]Y[UNIMOD:21]YQLNSK[UNI...,[TMT_TUM_mod_pY],"[0, 1, 0, 0, 0, 0]","[33397, 33470, 33322, 33180, 33248, 33538, 331...","[0, 1, 0, 0, 0, 0]","[02523_BA7-TMT_TUM_mod_pY_7_01_01-TMT1-1h-R1, ..."

In [33]:
combined_df.to_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow")

In [4]:
import pyarrow.parquet as pq
parquet_file = pq.ParquetFile("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet")
parquet_file.schema

<pyarrow._parquet.ParquetSchema object at 0x7f1ee6b74240>
required group field_id=-1 schema {
  optional binary field_id=-1 modified_sequence (String);
  optional group field_id=-1 raw_file (List) {
    repeated group field_id=-1 list {
      optional binary field_id=-1 element (String);
    }
  }
  optional group field_id=-1 scan_number (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional group field_id=-1 package (List) {
    repeated group field_id=-1 list {
      optional binary field_id=-1 element (String);
    }
  }
  optional group field_id=-1 most_abundant_charge_state (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional group field_id=-1 observed_charge_states (List) {
    repeated group field_id=-1 list {
      optional int64 field_id=-1 element;
    }
  }
  optional group field_id=-1 charge_state_dist (List) {
    repeated group field_id=-1 list {
      optional double field_id=-1 element;
    }
  }
}

In [34]:
read_combined = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow")

ArrowNotImplementedError: Nested data conversions not implemented for chunked array outputs

In [35]:
from datasets import load_dataset
load_dataset("parquet", data_files="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet")

Generating train split: 0 examples [00:00, ? examples/s]

DatasetGenerationError: An error occurred while generating the dataset

In [31]:
combined_df.charge_state_dist.iloc[0]

[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]

In [20]:
combined_df[["charge_state_dist", "modified_sequence"]].to_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow", index=False)

In [21]:
df = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/temp.parquet", engine="pyarrow")

In [24]:
df["modified_sequence"].iloc[0]

'AAAAAAAAAAR[UNIMOD:34]'

In [14]:
combined_df["raw_file"].apply(lambda x: type(x)).value_counts()

raw_file
<class 'numpy.ndarray'>    1632197
Name: count, dtype: int64

In [29]:
from datasets import load_dataset
load_dataset("parquet", data_files="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_pyarrow.parquet")

Generating train split: 0 examples [00:00, ? examples/s]

DatasetGenerationError: An error occurred while generating the dataset

In [28]:
df = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_pyarrow.parquet", engine="pyarrow")

ArrowNotImplementedError: Nested data conversions not implemented for chunked array outputs

In [ ]:
df["charge_state_dist"].iloc[0]

'[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]'

## Removing duplicates

In [11]:
before = df.shape[0]
df = df.drop_duplicates(subset=["modified_sequence"], keep="first")
after = df.shape[0]

print(f"Removed {before - after} duplicate rows based on modified_sequence column.")
print(f"Final DataFrame shape: {df.shape}")

Removed 10268 duplicate rows based on modified_sequence column.
Final DataFrame shape: (1621929, 7)

In [25]:
df.to_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_processed.parquet", engine="pyarrow")

In [9]:
final_df = pd.read_parquet("/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/combined_data/combined_data_processed.parquet", engine="pyarrow")

final_df.head()

,modified_sequence,raw_file,scan_number,package,most_abundant_charge_state,observed_charge_states,charge_state_dist
0,AAAAAAAAAAR[UNIMOD:34],['02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2...,"[9033, 9078, 9119, 9164, 9121, 9120, 9034, 916...",['TUM_mod_monomethyl'],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
1,AAAAAAAAAVS[UNIMOD:21]R,"['02747a_GD6-TUM_mod_pS_42_01_01-DDA-1h-R1', '...","[16293, 16304, 12004, 12005, 12003, 12002, 120...",['TUM_mod_pS'],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
2,AAAAAAAAVPSAGPAGPAPT[UNIMOD:21]SAAGR,['02588a_BD6-TUM_mod_pT_42_01_01-2xIT_2xHCD-1h...,"[22779, 22804, 22780]",['TUM_mod_pT'],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
3,AAAAAAALQAK,"['02468b_BE2-TUM_mod_ubi_50_01_01-DDA-1h-R1', ...","[16731, 16740, 16908, 16912, 16343, 16345, 165...",['TUM_mod_ubi'],"[0, 1, 0, 0, 0, 0]","[0, 1, 0, 0, 0, 0]","[0.0, 1.0, 0.0, 0.0, 0.0, 0.0]"
4,AAAAAAALQAKSDEK,['02195a_GD7-TUM_mod_acetylated_43_01_01-DDA-1...,"[13272, 13458]",['TUM_mod_acetylated'],"[0, 0, 1, 0, 0, 0]","[0, 0, 1, 0, 0, 0]","[0.0, 0.0, 1.0, 0.0, 0.0, 0.0]"

In [7]:
import ast
print(final_df.loc[0, "scan_number"])
print(final_df.loc[0, "raw_file"])
print(len(ast.literal_eval(final_df.loc[0, "scan_number"])))
print(len(ast.literal_eval(final_df.loc[0, "raw_file"])))

[9033, 9078, 9119, 9164, 9121, 9120, 9034, 9165, 9079, 9217, 9080, 9166, 9167, 9122, 9035, 9036, 9220, 10639, 9081, 9219, 10642, 9280, 10641, 9278, 9218, 10640, 9281, 9279, 8032, 8097, 8033, 8066, 8067, 8098, 8031, 8136, 8137, 8138, 8065, 8096, 8178, 8177, 8176, 8224, 8222, 8223, 9437, 9580, 9438, 10822, 9581, 10821, 9380, 9381, 9538, 9537, 10823, 10822]
['02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-2xIT_2xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-3xHCD-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02307a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R1', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3', '02320a_BH1-TUM_mod_monomethyl_8_01_01-DDA-1h-R3']
58
58

In [10]:
print(final_df.loc[10000, "charge_state_dist"])

[0.0, 0.23676550239555022, 0.7632344976044498, 0.0, 0.0, 0.0]

In [10]:
# the number of rows where the length of package is not 1
print(final_df[final_df["package"].apply(lambda x: len(ast.literal_eval(x)) != 1)].shape[0])
# print one of those 
print(final_df[final_df["package"].apply(lambda x: len(ast.literal_eval(x)) != 1)].iloc[0])

60420
modified_sequence                                                   AAAAELSLLEK
raw_file                      ['02468b_BE7-TUM_mod_ubi_55_01_01-DDA-1h-R1', ...
scan_number                                        [43489, 43486, 47062, 29029]
package                                         ['TUM_mod_ubi', 'TUM_nterm_ac']
most_abundant_charge_state                                   [0, 1, 0, 0, 0, 0]
observed_charge_states                                       [0, 1, 0, 0, 0, 0]
charge_state_dist                                [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
Name: 20, dtype: object

# Combined Processing // NOT (yet?!) WORKING

The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure.

In [ ]:
process_pcp_data.annotate_data(
    data_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/downloaded_data",
    andromeda_threshold=70,
    intensity_column="precursor_intensity",
    columns_to_keep=["modified_sequence", "precursor_charge", "precursor_intensity", "raw_file", "scan_number", "package"],
    min_count=None,
    aggregation="max",
    save_dir="/mnt/c/Users/Florian/Desktop/Uni/MSc/FoPr/PROSPECT/processed_data/combined_data",
    file_name="combined_dataset_processed.parquet",
    process_test_ptm_only=False
)